export const LOAD_SKILLS_ASYNC = 'LOAD_SKILLS_ASYNC';
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';

export const LOAD_ABOUTS_ASYNC = 'LOAD_ABOUTS_ASYNC';
export const LOAD_ABOUTS_SUCCESS = 'LOAD_ABOUTS_SUCCESS';

export const LOAD_CONTACTS_ASYNC = 'LOAD_CONTACTS_ASYNC';
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS';